export default {
  UPDATE_TEXT: 'UPDATE_TEXT',
  SHOW_LOADING: 'SHOW_LOADING',
  DISMISS_LOADING: 'DISMISS_LOADING',
  UPDATE_LINE_LIST: 'UPDATE_LINE_LIST',
  SELECT_PREFECTURE: 'SELECT_PREFECTURE',
};
